/**
 * ISSUE-029 authorization acceptance against the REAL local stack: real Supabase Auth
 * sessions, real Postgres (RLS role `app_server`), real HTTP through the Fastify app.
 * No mocks, no service re-implementation.
 *
 * Covers:
 *  - F-03  room visibility: a `roomId` join never bypasses LOCKED/CODE_ONLY.
 *  - ISSUE-011 role/grant binding: WATCH vs PLAY grants, single-use PLAYER codes.
 *  - ISSUE-016 viewer cap (5 WATCH) and spectator revocation on LOCKED (F-07).
 *  - ISSUE-029 deny matrix: anonymous / non-member / revoked viewer across the
 *    sensitive read + write routes, forged actor fields, spectator privilege.
 *  - ISSUE-008 ONBOARDING_REQUIRED gate for a profile whose username is NULL.
 *
 * Integration lane only (vitest.integration.config.ts). The unit lane also globs
 * tests/integration/**, where `runIf` skips these instead of faking a pass.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import crypto from 'node:crypto';
import {
  onRealtimeEvent,
  type RealtimeEventMap,
  type RealtimeEventName,
} from '../../apps/server/src/realtime/events.js';
import {
  INTEGRATION_LANE_ENV,
  createTestContext,
  resetTestData,
  resolveTestEnv,
  type TestContext,
} from '../fixtures/integration.js';

const inIntegrationLane = process.env[INTEGRATION_LANE_ENV] === '1';

const bearer = (accessToken: string) => ({ authorization: `Bearer ${accessToken}` });

/** 8-char room code alphabet (no 0/O/1/I) as generated by the invitations service. */
const CODE_RE = /^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{8}$/;

type CapturedEvent = {
  [E in RealtimeEventName]: { event: E; payload: RealtimeEventMap[E] };
}[RealtimeEventName];

/** Attach an in-process listener and record every realtime emit (spec 04 transport). */
function captureEvents(): { events: CapturedEvent[]; stop: () => void } {
  const events: CapturedEvent[] = [];
  const stop = onRealtimeEvent({
    publish(event, payload) {
      events.push({ event, payload } as CapturedEvent);
    },
  });
  return { events, stop };
}

/** Real Supabase password grant — the same flow the login route proxies. */
async function signIn(credentials: { email: string; password: string }): Promise<string> {
  const env = resolveTestEnv();
  const response = await fetch(`${env.supabaseUrl}/auth/v1/token?grant_type=password`, {
    method: 'POST',
    headers: { apikey: env.supabasePublishableKey, 'Content-Type': 'application/json' },
    body: JSON.stringify(credentials),
  });
  const body = (await response.json().catch(() => null)) as { access_token?: string } | null;
  if (!response.ok || !body?.access_token) {
    throw new Error(`[ISSUE-029] Supabase password sign-in failed (${response.status})`);
  }
  return body.access_token;
}

describe.runIf(inIntegrationLane)('ISSUE-029: authorization on the real stack', () => {
  let ctx: TestContext;

  beforeAll(async () => {
    ctx = await createTestContext();
  });

  afterAll(async () => {
    if (ctx) {
      await resetTestData(ctx.runId, ctx.adminPool);
      await ctx.dispose();
    }
  });

  const get = (url: string, accessToken?: string) =>
    ctx.app.inject({ method: 'GET', url, ...(accessToken ? { headers: bearer(accessToken) } : {}) });

  const post = (url: string, accessToken: string, payload: unknown) =>
    ctx.app.inject({ method: 'POST', url, headers: bearer(accessToken), payload });

  const patch = (
    url: string,
    accessToken: string,
    payload: unknown,
    headers: Record<string, string> = {},
  ) => ctx.app.inject({ method: 'PATCH', url, headers: { ...bearer(accessToken), ...headers }, payload });

  const join = (accessToken: string, body: { roomId?: string; code?: string; token?: string; role: string }) =>
    post('/api/v1/rooms/join', accessToken, body);

  async function createRoom(
    accessToken: string,
    body: { name: string; visibility: 'PUBLIC' | 'CODE_ONLY' | 'LOCKED' },
  ) {
    const res = await post('/api/v1/rooms', accessToken, body);
    expect(res.statusCode, `create room ${JSON.stringify(body)}`).toBe(200);
    return res.json().data as {
      id: string;
      visibility: string;
      roomVersion: number;
      currentMatchId: string | null;
      members: { userId: string; role: string; side: string | null; ready: boolean }[];
    };
  }

  /** Owner leaves a WAITING room, which closes it and frees every member's active slot. */
  async function closeRoom(accessToken: string, roomId: string) {
    const res = await post(`/api/v1/rooms/${roomId}/leave`, accessToken, { confirmResign: false });
    expect(res.statusCode, `close room ${roomId}`).toBe(200);
    expect(res.json().data.closed).toBe(true);
  }

  async function membershipOf(roomId: string, userId: string) {
    const res = await ctx.pool.query<{ role: string; ready: boolean }>(
      'SELECT role, ready FROM public.room_members WHERE room_id = $1 AND user_id = $2',
      [roomId, userId],
    );
    return res.rows;
  }

  describe('F-03: room visibility is enforced for roomId joins', () => {
    it('F-03: a LOCKED room rejects a roomId join for both PLAYER and SPECTATOR', async () => {
      const { A, B } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `locked-${ctx.runId}`, visibility: 'LOCKED' });
      try {
        for (const role of ['PLAYER', 'SPECTATOR'] as const) {
          const denied = await join(B.accessToken, { roomId: room.id, role });
          expect(denied.statusCode, `LOCKED ${role}`).toBe(403);
          expect(denied.json().error.code, `LOCKED ${role}`).toBe('INVITE_INVALID');
        }

        // The denial left no membership behind and a non-member cannot even read the room.
        expect(await membershipOf(room.id, B.id)).toEqual([]);
        const read = await get(`/api/v1/rooms/${room.id}`, B.accessToken);
        expect(read.statusCode).toBe(403);
        expect(read.json().error.code).toBe('FORBIDDEN');

        // Positive control: the owner still reads their own LOCKED room.
        const owner = await get(`/api/v1/rooms/${room.id}`, A.accessToken);
        expect(owner.statusCode).toBe(200);
        expect(owner.json().data).toMatchObject({ id: room.id, visibility: 'LOCKED' });
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('F-03: a CODE_ONLY room rejects a roomId join for both PLAYER and SPECTATOR', async () => {
      const { A, B } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `code-${ctx.runId}`, visibility: 'CODE_ONLY' });
      try {
        for (const role of ['PLAYER', 'SPECTATOR'] as const) {
          const denied = await join(B.accessToken, { roomId: room.id, role });
          expect(denied.statusCode, `CODE_ONLY ${role}`).toBe(403);
          expect(denied.json().error.code, `CODE_ONLY ${role}`).toBe('INVITE_INVALID');
        }
        expect(await membershipOf(room.id, B.id)).toEqual([]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('positive control: a PUBLIC room accepts a roomId join for PLAYER and SPECTATOR', async () => {
      const { A, B, S6 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `public-${ctx.runId}`, visibility: 'PUBLIC' });
      try {
        const asPlayer = await join(B.accessToken, { roomId: room.id, role: 'PLAYER' });
        expect(asPlayer.statusCode).toBe(200);
        expect(
          asPlayer.json().data.members.find((m: { userId: string }) => m.userId === B.id),
        ).toMatchObject({ role: 'PLAYER', side: 'BLACK' }); // owner A holds RED

        const asSpectator = await join(S6.accessToken, { roomId: room.id, role: 'SPECTATOR' });
        expect(asSpectator.statusCode).toBe(200);
        expect(
          asSpectator.json().data.members.find((m: { userId: string }) => m.userId === S6.id),
        ).toMatchObject({ role: 'SPECTATOR', side: null });
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });
  });

  describe('ISSUE-011: grants are bound to the role they were issued for', () => {
    it('an unknown code or token cannot enter a room (403 INVITE_INVALID)', async () => {
      const { A, B } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `unknown-${ctx.runId}`, visibility: 'CODE_ONLY' });
      try {
        for (const locator of [{ code: 'ZZZZZZZZ' }, { token: 'not-a-real-token' }] as const) {
          const denied = await join(B.accessToken, { ...locator, role: 'PLAYER' });
          expect(denied.statusCode, `${JSON.stringify(locator)} body: ${denied.body}`).toBe(403);
          expect(denied.json().error.code, JSON.stringify(locator)).toBe('INVITE_INVALID');
        }
        expect(await membershipOf(room.id, B.id)).toEqual([]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('a WATCH grant cannot be spent as PLAYER and vice versa', async () => {
      const { A, B, S1, S2 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `grants-${ctx.runId}`, visibility: 'CODE_ONLY' });
      try {
        const watch = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, { rotate: false });
        expect(watch.statusCode, `watch-code body: ${watch.body}`).toBe(200);
        const watchCode = watch.json().data.code as string;
        expect(watchCode).toMatch(CODE_RE);

        const asPlayer = await join(B.accessToken, { code: watchCode, role: 'PLAYER' });
        expect(asPlayer.statusCode).toBe(403);
        expect(asPlayer.json().error.code).toBe('INVITE_INVALID');

        const asSpectator = await join(S1.accessToken, { code: watchCode, role: 'SPECTATOR' });
        expect(asSpectator.statusCode).toBe(200);
        expect(
          asSpectator.json().data.members.find((m: { userId: string }) => m.userId === S1.id),
        ).toMatchObject({ role: 'SPECTATOR' });

        // Vice versa: a PLAYER grant offered with role SPECTATOR is refused.
        const playerInvite = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
          role: 'PLAYER',
        });
        expect(playerInvite.statusCode, `invitations body: ${playerInvite.body}`).toBe(200);
        const playerCode = playerInvite.json().data.code as string;
        expect(playerCode).toMatch(CODE_RE);

        const viceVersa = await join(S2.accessToken, { code: playerCode, role: 'SPECTATOR' });
        expect(viceVersa.statusCode).toBe(403);
        expect(viceVersa.json().error.code).toBe('INVITE_INVALID');
        expect(await membershipOf(room.id, S2.id)).toEqual([]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('an 8-char PLAYER code is single use', async () => {
      const { A, S1, S2 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `single-${ctx.runId}`, visibility: 'CODE_ONLY' });
      try {
        const invite = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, { role: 'PLAYER' });
        expect(invite.statusCode, `invitations body: ${invite.body}`).toBe(200);
        const code = invite.json().data.code as string;
        expect(code).toMatch(CODE_RE);

        const first = await join(S1.accessToken, { code, role: 'PLAYER' });
        expect(first.statusCode).toBe(200);
        expect(first.json().data.members.filter((m: { role: string }) => m.role === 'PLAYER')).toHaveLength(2);

        const second = await join(S2.accessToken, { code, role: 'PLAYER' });
        expect(second.statusCode).toBe(403);
        expect(second.json().error.code).toBe('INVITE_INVALID');

        // The grant is consumed, not merely unusable, and the loser has no seat.
        const grant = await ctx.pool.query<{ status: string }>(
          'SELECT status FROM public.invitations WHERE room_id = $1',
          [room.id],
        );
        expect(grant.rows[0]?.status).toBe('CONSUMED');
        expect(await membershipOf(room.id, S2.id)).toEqual([]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });
  });

  describe('ISSUE-016: the 5-viewer cap holds inside the room lock', () => {
    it('the 6th spectator is rejected with ROOM_FULL and no row is written', async () => {
      const { A, S1, S2, S3, S4, S5, S6 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `cap-${ctx.runId}`, visibility: 'PUBLIC' });
      try {
        for (const spectator of [S1, S2, S3, S4, S5]) {
          const res = await join(spectator.accessToken, { roomId: room.id, role: 'SPECTATOR' });
          expect(res.statusCode, `spectator ${spectator.username}`).toBe(200);
        }

        const sixth = await join(S6.accessToken, { roomId: room.id, role: 'SPECTATOR' });
        expect(sixth.statusCode).toBe(409);
        expect(sixth.json().error.code).toBe('ROOM_FULL');

        const count = await ctx.pool.query<{ count: number }>(
          "SELECT count(*)::int AS count FROM public.room_members WHERE room_id = $1 AND role = 'SPECTATOR'",
          [room.id],
        );
        expect(count.rows[0]?.count).toBe(5);
        expect(await membershipOf(room.id, S6.id)).toEqual([]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('a spectator cannot ready in a WAITING room: only PLAYER can be ready', async () => {
      const { A, S1 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `sp-ready-${ctx.runId}`, visibility: 'PUBLIC' });
      try {
        expect((await join(S1.accessToken, { roomId: room.id, role: 'SPECTATOR' })).statusCode).toBe(200);
        const ready = await post(`/api/v1/rooms/${room.id}/ready`, S1.accessToken, { ready: true });
        expect(ready.statusCode).toBe(400);
        expect(ready.json().error.code).toBe('VALIDATION_ERROR');
        expect(await membershipOf(room.id, S1.id)).toEqual([{ role: 'SPECTATOR', ready: false }]);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });

    it('two simultaneous joins for the last seat admit exactly one viewer', async () => {
      const { A, S1, S2, S3, S4, S5, S6 } = ctx.users;
      const room = await createRoom(A.accessToken, { name: `cap-race-${ctx.runId}`, visibility: 'PUBLIC' });
      try {
        for (const spectator of [S1, S2, S3, S4]) {
          const res = await join(spectator.accessToken, { roomId: room.id, role: 'SPECTATOR' });
          expect(res.statusCode, `spectator ${spectator.username}`).toBe(200);
        }

        const [first, second] = await Promise.all([
          join(S5.accessToken, { roomId: room.id, role: 'SPECTATOR' }),
          join(S6.accessToken, { roomId: room.id, role: 'SPECTATOR' }),
        ]);
        expect([first.statusCode, second.statusCode].sort()).toEqual([200, 409]);

        const count = await ctx.pool.query<{ count: number }>(
          "SELECT count(*)::int AS count FROM public.room_members WHERE room_id = $1 AND role = 'SPECTATOR'",
          [room.id],
        );
        expect(count.rows[0]?.count).toBe(5);
        const admitted = [
          ...(await membershipOf(room.id, S5.id)),
          ...(await membershipOf(room.id, S6.id)),
        ];
        expect(admitted).toHaveLength(1);
      } finally {
        await closeRoom(A.accessToken, room.id);
      }
    });
  });

  describe('ISSUE-016/F-07 + ISSUE-029: revocation and the deny matrix on a live match', () => {
    let roomId: string;
    let matchId: string;

    beforeAll(async () => {
      const { A, B, S1, S2, S3, S4, S5, S6 } = ctx.users;
      // One real room with two players, five viewers and then a real ACTIVE match.
      roomId = (await createRoom(A.accessToken, { name: `matrix-${ctx.runId}`, visibility: 'PUBLIC' })).id;
      const playerJoin = await join(B.accessToken, { roomId, role: 'PLAYER' });
      expect(playerJoin.statusCode).toBe(200);

      for (const spectator of [S1, S2, S3, S4, S5]) {
        const res = await join(spectator.accessToken, { roomId, role: 'SPECTATOR' });
        expect(res.statusCode, `spectator ${spectator.username}`).toBe(200);
      }
      const overCap = await join(S6.accessToken, { roomId, role: 'SPECTATOR' });
      expect(overCap.statusCode).toBe(409);
      expect(overCap.json().error.code).toBe('ROOM_FULL');

      expect((await post(`/api/v1/rooms/${roomId}/ready`, A.accessToken, { ready: true })).statusCode).toBe(200);
      const started = await post(`/api/v1/rooms/${roomId}/ready`, B.accessToken, { ready: true });
      expect(started.statusCode).toBe(200);
      matchId = started.json().data.matchSnapshot.id as string;
      expect(matchId).toBeTruthy();
    });

    it('the cap held on the live room: five spectator rows, none for the rejected user', async () => {
      const { S6 } = ctx.users;
      const count = await ctx.pool.query<{ count: number }>(
        "SELECT count(*)::int AS count FROM public.room_members WHERE room_id = $1 AND role = 'SPECTATOR'",
        [roomId],
      );
      expect(count.rows[0]?.count).toBe(5);
      expect(await membershipOf(roomId, S6.id)).toEqual([]);
    });

    it('positive control: a player reads the match and the PLAYERS chat channel', async () => {
      const { A, B } = ctx.users;
      const snapshot = await get(`/api/v1/matches/${matchId}`, B.accessToken);
      expect(snapshot.statusCode).toBe(200);
      expect(snapshot.json().data).toMatchObject({
        id: matchId,
        roomId,
        status: 'ACTIVE',
        redUserId: A.id,
        blackUserId: B.id,
      });

      const chat = await get(`/api/v1/rooms/${roomId}/chat`, A.accessToken);
      expect(chat.statusCode).toBe(200);
      expect(chat.json().data.channel).toBe('PLAYERS');
    });

    it('a spectator cannot ready, move, or act through a takeover lease', async () => {
      const { B, S1 } = ctx.users;
      const ready = await post(`/api/v1/rooms/${roomId}/ready`, S1.accessToken, { ready: true });
      // The room is already PLAYING, so the state check answers first (409); the WAITING-room
      // case above proves the role check (400 VALIDATION_ERROR) for a spectator.
      expect(ready.statusCode, ready.body).toBe(409);
      expect(ready.json().error.code).toBe('CONFLICT');
      expect(await membershipOf(roomId, S1.id)).toEqual([{ role: 'SPECTATOR', ready: false }]);

      const move = await post(`/api/v1/matches/${matchId}/commands/move`, S1.accessToken, {
        commandId: crypto.randomUUID(),
        expectedVersion: 0,
        payload: { from: { x: 0, y: 9 }, to: { x: 0, y: 8 } },
      });
      expect(move.statusCode).toBe(403);
      expect(move.json().error.code).toBe('NOT_YOUR_TURN');
      const untouched = await ctx.pool.query<{ version: number; ply: number }>(
        'SELECT version, ply FROM public.matches WHERE id = $1',
        [matchId],
      );
      expect(untouched.rows[0]).toEqual({ version: 0, ply: 0 });

      // A forged actor in the takeover body is rejected before any write.
      const forged = await post('/api/v1/control/takeover', S1.accessToken, {
        tabId: crypto.randomUUID(),
        userId: B.id,
      });
      expect(forged.statusCode).toBe(400);
      expect(forged.json().error.code).toBe('VALIDATION_ERROR');

      // Even if a spectator obtains a lease, player-only media writes stay denied.
      const lease = await post('/api/v1/control/takeover', S1.accessToken, { tabId: crypto.randomUUID() });
      expect(lease.statusCode).toBe(200);
      const write = await patch(
        '/api/v1/media/policy',
        S1.accessToken,
        { matchId, kind: 'CAMERA', audience: 'OPPONENT_ONLY', policyVersion: 0 },
        {
          'x-control-id': lease.json().data.controllerId as string,
          'x-control-epoch': String(lease.json().data.controllerEpoch as number),
        },
      );
      expect(write.statusCode).toBe(403);
      expect(write.json().error.code).toBe('FORBIDDEN');
      const policy = await ctx.pool.query<{ count: number }>(
        'SELECT count(*)::int AS count FROM public.media_policies WHERE match_id = $1 AND user_id = $2',
        [matchId, S1.id],
      );
      expect(policy.rows[0]?.count).toBe(0);
    });

    it('F-07: locking the room revokes every spectator and emits access:revoked with the new version', async () => {
      const { A, S1, S2, S3, S4, S5 } = ctx.users;
      const storedVersion = await ctx.pool.query<{ room_version: number }>(
        'SELECT room_version FROM public.rooms WHERE id = $1',
        [roomId],
      );
      const capture = captureEvents();
      let response;
      try {
        response = await patch(`/api/v1/rooms/${roomId}`, A.accessToken, { visibility: 'LOCKED' });
      } finally {
        capture.stop();
      }
      expect(response.statusCode).toBe(200);
      expect(response.json().data.visibility).toBe('LOCKED');
      const roomVersionAfterLock = response.json().data.roomVersion as number;
      // Locking bumps room_version exactly once, on top of the version the DB holds.
      expect(roomVersionAfterLock).toBe(storedVersion.rows[0]!.room_version + 1);

      const remaining = await ctx.pool.query<{ count: number }>(
        "SELECT count(*)::int AS count FROM public.room_members WHERE room_id = $1 AND role = 'SPECTATOR'",
        [roomId],
      );
      expect(remaining.rows[0]?.count).toBe(0);
      const revokedIds: string[] = [];
      for (const spectator of [S1, S2, S3, S4, S5]) {
        expect(await membershipOf(roomId, spectator.id), `revoked ${spectator.username}`).toEqual([]);
        revokedIds.push(spectator.id);
      }

      const revoked = capture.events.filter(
        (event): event is Extract<CapturedEvent, { event: 'access:revoked' }> =>
          event.event === 'access:revoked',
      );
      expect(revoked).toHaveLength(1);
      expect(revoked[0]!.payload).toEqual({
        roomId,
        reason: 'ROOM_LOCKED',
        roomVersion: roomVersionAfterLock,
        userIds: expect.arrayContaining(revokedIds),
      });
      expect([...revoked[0]!.payload.userIds].sort()).toEqual([...revokedIds].sort());

      // The revoked viewer's controller lease cascaded away with the membership row.
      const controls = await ctx.pool.query<{ count: number }>(
        'SELECT count(*)::int AS count FROM public.client_controls WHERE room_id = $1',
        [roomId],
      );
      expect(controls.rows[0]?.count).toBe(0);
    });

    it('ISSUE-029: a revoked spectator gets no room/chat/replay/media data', async () => {
      const { S1 } = ctx.users;
      for (const [url, code] of [
        [`/api/v1/rooms/${roomId}`, 'FORBIDDEN'],
        [`/api/v1/matches/${matchId}/replay`, 'FORBIDDEN'],
        [`/api/v1/rooms/${roomId}/chat`, 'FORBIDDEN'],
        [`/api/v1/media/policy?matchId=${matchId}`, 'FORBIDDEN'],
      ] as const) {
        const res = await get(url, S1.accessToken);
        expect(res.statusCode, url).toBe(403);
        expect(res.json().error.code, url).toBe(code);
      }

      const send = await post(`/api/v1/rooms/${roomId}/chat`, S1.accessToken, {
        clientMessageId: crypto.randomUUID(),
        content: 'revoked viewer must not write',
      });
      // Chat send is control-gated (spec 04): a caller with no lease is refused before
      // membership is even considered, and either way nothing is written.
      expect(send.statusCode, send.body).toBe(403);
      expect(send.json().error.code).toBe('CONTROL_REQUIRED');

      const write = await patch('/api/v1/media/policy', S1.accessToken, {
        matchId,
        kind: 'CAMERA',
        audience: 'OPPONENT_ONLY',
        policyVersion: 0,
      });
      expect(write.statusCode).toBe(403);
      expect(write.json().error.code).toBe('FORBIDDEN');

      // History is participant-filtered: the revoked viewer never sees this match.
      const history = await get('/api/v1/history', S1.accessToken);
      expect(history.statusCode).toBe(200);
      expect((history.json().data as { id: string }[]).some((entry) => entry.id === matchId)).toBe(false);

      const chatRows = await ctx.pool.query<{ count: number }>(
        'SELECT count(*)::int AS count FROM public.chat_messages WHERE match_id = $1 AND sender_id = $2',
        [matchId, S1.id],
      );
      expect(chatRows.rows[0]?.count).toBe(0);
    });

    it('ISSUE-029: a non-member is denied the room, chat, replay and media reads', async () => {
      const { B, S6 } = ctx.users;
      for (const [url, code] of [
        [`/api/v1/rooms/${roomId}`, 'FORBIDDEN'],
        [`/api/v1/matches/${matchId}/replay`, 'FORBIDDEN'],
        [`/api/v1/rooms/${roomId}/chat`, 'FORBIDDEN'],
        [`/api/v1/media/policy?matchId=${matchId}`, 'FORBIDDEN'],
      ] as const) {
        const res = await get(url, S6.accessToken);
        expect(res.statusCode, url).toBe(403);
        expect(res.json().error.code, url).toBe(code);
      }

      const send = await post(`/api/v1/rooms/${roomId}/chat`, S6.accessToken, {
        clientMessageId: crypto.randomUUID(),
        content: 'stranger must not write',
      });
      expect(send.statusCode, send.body).toBe(403);
      expect(send.json().error.code).toBe('CONTROL_REQUIRED');
      const strangerMessages = await ctx.pool.query<{ count: number }>(
        'SELECT count(*)::int AS count FROM public.chat_messages WHERE match_id = $1 AND sender_id = $2',
        [matchId, S6.id],
      );
      expect(strangerMessages.rows[0]?.count).toBe(0);

      const history = await get('/api/v1/history', S6.accessToken);
      expect(history.statusCode).toBe(200);
      expect((history.json().data as { id: string }[]).some((entry) => entry.id === matchId)).toBe(false);

      // A player sees exactly the match they played (control for the filter above).
      const playerHistory = await get('/api/v1/history', B.accessToken);
      expect(playerHistory.statusCode).toBe(200);
      expect((playerHistory.json().data as { id: string }[]).some((entry) => entry.id === matchId)).toBe(true);
    });

    it('ISSUE-029: anonymous callers get 401 UNAUTHENTICATED on every sensitive route', async () => {
      for (const url of [
        `/api/v1/matches/${matchId}`,
        `/api/v1/matches/${matchId}/replay`,
        '/api/v1/history',
        `/api/v1/rooms/${roomId}`,
        `/api/v1/rooms/${roomId}/chat`,
        `/api/v1/media/policy?matchId=${matchId}`,
      ]) {
        const res = await get(url);
        expect(res.statusCode, url).toBe(401);
        expect(res.json().error.code, url).toBe('UNAUTHENTICATED');
      }

      const send = await ctx.app.inject({
        method: 'POST',
        url: `/api/v1/rooms/${roomId}/chat`,
        payload: { clientMessageId: crypto.randomUUID(), content: 'anonymous' },
      });
      expect(send.statusCode).toBe(401);
      expect(send.json().error.code).toBe('UNAUTHENTICATED');

      const write = await ctx.app.inject({
        method: 'PATCH',
        url: '/api/v1/media/policy',
        payload: { matchId, kind: 'CAMERA', audience: 'OPPONENT_ONLY', policyVersion: 0 },
      });
      expect(write.statusCode).toBe(401);
      expect(write.json().error.code).toBe('UNAUTHENTICATED');
    });

    it('forged role/actor/side/result/channel fields are rejected by schema validation', async () => {
      const { B, S6 } = ctx.users;
      const cases: { method: 'POST' | 'PATCH'; url: string; payload: unknown }[] = [
        {
          method: 'POST',
          url: `/api/v1/rooms/${roomId}/chat`,
          payload: { clientMessageId: crypto.randomUUID(), content: 'x', channel: 'SPECTATORS' },
        },
        { method: 'POST', url: `/api/v1/rooms/${roomId}/ready`, payload: { ready: true, role: 'PLAYER' } },
        {
          method: 'POST',
          url: '/api/v1/rooms/join',
          payload: { roomId, role: 'PLAYER', actorId: S6.id },
        },
        {
          method: 'POST',
          url: `/api/v1/matches/${matchId}/commands/move`,
          payload: {
            commandId: crypto.randomUUID(),
            expectedVersion: 0,
            payload: { from: { x: 0, y: 9 }, to: { x: 0, y: 8 } },
            side: 'BLACK',
            actorId: B.id,
          },
        },
        {
          method: 'POST',
          url: `/api/v1/matches/${matchId}/commands/resign`,
          payload: { commandId: crypto.randomUUID(), expectedVersion: 0, payload: {}, result: 'RED' },
        },
        {
          method: 'POST',
          url: '/api/v1/control/takeover',
          payload: { tabId: crypto.randomUUID(), controllerId: B.id },
        },
      ];

      for (const entry of cases) {
        const res = await ctx.app.inject({
          method: entry.method,
          url: entry.url,
          headers: bearer(B.accessToken),
          payload: entry.payload,
        });
        expect(res.statusCode, `${entry.method} ${entry.url}`).toBe(400);
        expect(res.json().error.code, `${entry.method} ${entry.url}`).toBe('VALIDATION_ERROR');
      }

      // No escalation landed: the stranger still has no seat, the match is unplayed.
      expect(await membershipOf(roomId, S6.id)).toEqual([]);
      const match = await ctx.pool.query<{ version: number }>(
        'SELECT version FROM public.matches WHERE id = $1',
        [matchId],
      );
      expect(match.rows[0]?.version).toBe(0);
    });

    it('ISSUE-029: GET /matches/:id denies a non-member (IDOR)', async () => {
      const { S6 } = ctx.users;
      const res = await get(`/api/v1/matches/${matchId}`, S6.accessToken);
      expect(res.statusCode, res.body).toBe(403);
      expect(res.json().error.code).toBe('FORBIDDEN');
    });

    it('ISSUE-029: GET /matches/:id denies a revoked spectator (IDOR)', async () => {
      const { S1 } = ctx.users;
      const res = await get(`/api/v1/matches/${matchId}`, S1.accessToken);
      expect(res.statusCode, res.body).toBe(403);
      expect(res.json().error.code).toBe('FORBIDDEN');
    });
  });

  describe('ISSUE-008: ONBOARDING_REQUIRED gate for a NULL username', () => {
    /**
     * The fixture needs a real login session whose `public.profiles.username` is NULL.
     * `createAuthUser` cannot produce it: the local `handle_new_user` trigger raises
     * "signup_username is required for email signup" for an email signup, and phone
     * logins are disabled in the local stack (`phone_provider_disabled`). So the user is
     * created with a phone only (provider `phone` → trigger stores a NULL username) and an
     * email identity is then attached through the Admin API; the trigger does not re-run,
     * the profile keeps username NULL, and a normal email password grant works.
     */
    async function createUnonboardedUser(): Promise<{ id: string; accessToken: string }> {
      const env = resolveTestEnv();
      // Each call needs a distinct email: the suite creates one unonboarded user per test
      // and Supabase rejects a duplicate email with 23505 (users_email_partial_key).
      const email = `onb_${ctx.runId}_${crypto.randomUUID().slice(0, 8)}@local.test`;
      const adminHeaders = {
        apikey: env.supabaseSecretKey,
        Authorization: `Bearer ${env.supabaseSecretKey}`,
        'Content-Type': 'application/json',
      };
      const created = await fetch(`${env.supabaseUrl}/auth/v1/admin/users`, {
        method: 'POST',
        headers: adminHeaders,
        body: JSON.stringify({
          phone: `+8491${crypto.randomInt(1000000, 9999999)}`,
          password: 'LocalTest12345',
          phone_confirm: true,
          user_metadata: { test_run_id: ctx.runId },
        }),
      });
      const createdBody = (await created.json().catch(() => null)) as { id?: string } | null;
      if (!created.ok || !createdBody?.id) {
        throw new Error(`[ISSUE-029] Admin createUser failed (${created.status}): ${await created.text()}`);
      }

      const attached = await fetch(`${env.supabaseUrl}/auth/v1/admin/users/${createdBody.id}`, {
        method: 'PUT',
        headers: adminHeaders,
        body: JSON.stringify({ email, email_confirm: true, password: 'LocalTest12345' }),
      });
      if (!attached.ok) {
        throw new Error(`[ISSUE-029] Admin attach email failed (${attached.status}): ${await attached.text()}`);
      }

      const accessToken = await signIn({ email, password: 'LocalTest12345' });
      const profile = await ctx.pool.query<{ username: string | null }>(
        'SELECT username FROM public.profiles WHERE user_id = $1',
        [createdBody.id],
      );
      expect(profile.rows[0]?.username).toBeNull(); // fixture precondition, from the DB
      return { id: createdBody.id, accessToken };
    }

    it('GET /me and complete-profile stay open, and normal routes open afterwards', async () => {
      const user = await createUnonboardedUser();
      const username = `xq_onb_${ctx.runId}`;

      const me = await get('/api/v1/me', user.accessToken);
      expect(me.statusCode).toBe(200);
      expect(me.json().data).toMatchObject({ onboardingRequired: true });
      expect(me.json().data.profile).toMatchObject({ id: user.id, username: null });

      const complete = await post('/api/v1/auth/complete-profile', user.accessToken, {
        username,
        displayName: 'Onboarded',
      });
      expect(complete.statusCode).toBe(200);
      expect(complete.json().data).toMatchObject({ id: user.id, username });

      const after = await get('/api/v1/me', user.accessToken);
      expect(after.statusCode).toBe(200);
      expect(after.json().data.onboardingRequired).toBe(false);

      const normal = await get('/api/v1/friends', user.accessToken);
      expect(normal.statusCode).toBe(200);
    });

    /**
     * Spec 04 declares the `ONBOARDING_REQUIRED` error code and ISSUE-008 requires
     * "game API ONBOARDING_REQUIRED" for a profile without a username. The gate lives in
     * `apps/server/src/auth/onboarding-gate.ts`; `registerOnboardingGate(app)` must run in
     * `createApp()` before the feature routes are registered so these normal routes are gated.
     */
    it('an unonboarded user is blocked with ONBOARDING_REQUIRED', async () => {
      const user = await createUnonboardedUser();

      for (const url of ['/api/v1/friends', '/api/v1/rooms']) {
        const res = await get(url, user.accessToken);
        expect(res.statusCode, url).toBe(403);
        expect(res.json().error.code, url).toBe('ONBOARDING_REQUIRED');
      }
    });
  });
});
