/**
 * ISSUE-011 acceptance against the REAL local stack: real Supabase Auth sessions,
 * real Postgres (RLS role `app_server`), real HTTP through the Fastify app.
 *
 * Covers the invitation schema path end-to-end (`public.invitations` has
 * `sender_id`/`role PLAY|WATCH`/`status ACTIVE|CONSUMED|...` and 32-byte
 * `token_hash`/`code_hash`, spec 09 §5.4): direct PLAY invites, code+token WATCH
 * grants, single-use PLAY consumption, rotation, expiry, re-issue dedup, the
 * room-close revocation path and the ONBOARDING_REQUIRED gate.
 *
 * Integration lane only. The unit lane also globs `tests/integration/**`, where
 * `runIf` skips this file instead of faking a pass.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import crypto from 'node:crypto';
import {
  INTEGRATION_LANE_ENV,
  createTestContext,
  resetTestData,
  resolveTestEnv,
  type TestContext,
  type TestUser,
} from '../fixtures/integration.js';

const inIntegrationLane = process.env[INTEGRATION_LANE_ENV] === '1';

const bearer = (accessToken: string) => ({ authorization: `Bearer ${accessToken}` });

/** 8-char room code alphabet (no 0/O/1/I) as generated by the invitations service. */
const CODE_RE = /^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{8}$/;

interface InvitationRow {
  id: string;
  sender_id: string;
  recipient_id: string | null;
  role: string;
  status: string;
  epoch: number;
  token_hash: Buffer | null;
  code_hash: Buffer | null;
  consumed_by: string | null;
  resolved_at: string | null;
  expires_at: string;
  created_at: string;
}

/** Real Supabase password grant — the same flow the login route proxies. */
async function signIn(credentials: { email: string; password: string }): Promise<string> {
  const env = resolveTestEnv();
  const response = await fetch(`${env.supabaseUrl}/auth/v1/token?grant_type=password`, {
    method: 'POST',
    headers: { apikey: env.supabasePublishableKey, 'Content-Type': 'application/json' },
    body: JSON.stringify(credentials),
  });
  const body = (await response.json().catch(() => null)) as { access_token?: string } | null;
  if (!response.ok || !body?.access_token) {
    throw new Error(`[invitations] Supabase password sign-in failed (${response.status})`);
  }
  return body.access_token;
}

describe.runIf(inIntegrationLane)('ISSUE-011: invitations and role-bound joins on the real stack', () => {
  let ctx: TestContext;

  beforeAll(async () => {
    ctx = await createTestContext();
  });

  afterAll(async () => {
    if (ctx) {
      await resetTestData(ctx.runId, ctx.adminPool);
      await ctx.dispose();
    }
  });

  const post = (url: string, accessToken: string, payload: unknown) =>
    ctx.app.inject({ method: 'POST', url, headers: bearer(accessToken), payload });

  const get = (url: string, accessToken: string) =>
    ctx.app.inject({ method: 'GET', url, headers: bearer(accessToken) });

  async function createRoom(accessToken: string, visibility: 'PUBLIC' | 'CODE_ONLY' | 'LOCKED') {
    const res = await post('/api/v1/rooms', accessToken, {
      name: `inv-${ctx.runId}`,
      visibility,
    });
    expect(res.statusCode, `create room ${visibility}`).toBe(200);
    return res.json().data as { id: string };
  }

  /** Owner leaves a WAITING room, which closes it and frees every member's slot. */
  async function closeRoom(accessToken: string, roomId: string) {
    const res = await post(`/api/v1/rooms/${roomId}/leave`, accessToken, { confirmResign: false });
    expect(res.statusCode, `close room ${roomId}`).toBe(200);
    expect(res.json().data.closed).toBe(true);
  }

  /** Direct invites require an ACCEPTED friendship; seed it as fixture data. */
  async function makeFriends(a: TestUser, b: TestUser) {
    const [low, high] = a.id < b.id ? [a.id, b.id] : [b.id, a.id];
    await ctx.adminPool.query(
      `INSERT INTO public.friend_relations (user_low, user_high, requester_id, status, accepted_at)
       VALUES ($1, $2, $1, 'ACCEPTED', now())
       ON CONFLICT (user_low, user_high) DO UPDATE SET status = 'ACCEPTED', accepted_at = now()`,
      [low, high],
    );
  }

  async function membershipOf(roomId: string, userId: string) {
    const res = await ctx.pool.query<{ role: string; side: string | null }>(
      'SELECT role, side FROM public.room_members WHERE room_id = $1 AND user_id = $2',
      [roomId, userId],
    );
    return res.rows;
  }

  async function invitationOf(id: string): Promise<InvitationRow | undefined> {
    const res = await ctx.pool.query<InvitationRow>(
      'SELECT * FROM public.invitations WHERE id = $1',
      [id],
    );
    return res.rows[0];
  }

  it('a direct PLAY invitation is recipient-bound, accepted once, and grants the seat', async () => {
    const { A, B } = ctx.users;
    await makeFriends(A, B);
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const created = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        recipientId: B.id,
      });
      expect(created.statusCode, created.body).toBe(200);
      const dto = created.json().data as Record<string, unknown>;
      expect(dto).toMatchObject({
        roomId: room.id,
        inviterId: A.id,
        recipientId: B.id,
        role: 'PLAYER',
        code: null,
        status: 'PENDING',
      });

      const row = await invitationOf(dto.id as string);
      expect(row).toMatchObject({
        sender_id: A.id,
        recipient_id: B.id,
        role: 'PLAY',
        status: 'ACTIVE',
        epoch: 0,
        token_hash: null,
        code_hash: null,
        consumed_by: null,
        resolved_at: null,
      });

      const inbox = await get('/api/v1/invitations', B.accessToken);
      expect(inbox.statusCode).toBe(200);
      expect(
        (inbox.json().data as { id: string; status: string }[]).find((i) => i.id === dto.id),
      ).toMatchObject({ status: 'PENDING' });

      const accepted = await post(`/api/v1/invitations/${dto.id as string}/respond`, B.accessToken, {
        accept: true,
      });
      expect(accepted.statusCode, accepted.body).toBe(200);
      expect(
        (accepted.json().data.members as { userId: string; role: string; side: string | null }[]).find(
          (m) => m.userId === B.id,
        ),
      ).toMatchObject({ role: 'PLAYER', side: 'BLACK' });
      expect(await membershipOf(room.id, B.id)).toEqual([{ role: 'PLAYER', side: 'BLACK' }]);

      const consumed = await invitationOf(dto.id as string);
      expect(consumed?.status).toBe('CONSUMED');
      expect(consumed?.consumed_by).toBe(B.id);
      expect(consumed?.resolved_at).not.toBeNull();
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('a declining recipient marks the invitation DECLINED and never gets a seat', async () => {
    const { A, B } = ctx.users;
    await makeFriends(A, B);
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const created = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        recipientId: B.id,
      });
      const id = created.json().data.id as string;

      const declined = await post(`/api/v1/invitations/${id}/respond`, B.accessToken, {
        accept: false,
      });
      expect(declined.statusCode, declined.body).toBe(200);
      expect(declined.json().data).toEqual({ removed: true });

      const row = await invitationOf(id);
      expect(row?.status).toBe('DECLINED');
      expect(row?.resolved_at).not.toBeNull();
      expect(await membershipOf(room.id, B.id)).toEqual([]);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('watch-code issues one share grant with 32-byte hashes, reusable by code and by token', async () => {
    const { A, S1, S2, S3 } = ctx.users;
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const grant = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: false,
      });
      expect(grant.statusCode, grant.body).toBe(200);
      const code = grant.json().data.code as string;
      const token = grant.json().data.token as string;
      expect(code).toMatch(CODE_RE);
      expect(token).toMatch(/^[0-9a-f]{64}$/);

      const row = await ctx.pool.query<InvitationRow>(
        `SELECT *, octet_length(code_hash) AS code_len, octet_length(token_hash) AS token_len
           FROM public.invitations WHERE room_id = $1`,
        [room.id],
      );
      const stored = row.rows[0] as InvitationRow & { code_len: number; token_len: number };
      expect(stored).toMatchObject({
        sender_id: A.id,
        recipient_id: null,
        role: 'WATCH',
        status: 'ACTIVE',
        code_len: 32,
        token_len: 32,
      });
      expect(stored.code_hash!.equals(stored.token_hash!)).toBe(false);

      const byCode = await post('/api/v1/rooms/join', S1.accessToken, { code, role: 'SPECTATOR' });
      expect(byCode.statusCode, byCode.body).toBe(200);
      expect(await membershipOf(room.id, S1.id)).toEqual([{ role: 'SPECTATOR', side: null }]);

      const byToken = await post('/api/v1/rooms/join', S2.accessToken, { token, role: 'SPECTATOR' });
      expect(byToken.statusCode, byToken.body).toBe(200);
      expect(await membershipOf(room.id, S2.id)).toEqual([{ role: 'SPECTATOR', side: null }]);

      // A WATCH grant cannot be spent as PLAYER, and nothing is written for the attempt.
      const wrongRole = await post('/api/v1/rooms/join', S3.accessToken, { code, role: 'PLAYER' });
      expect(wrongRole.statusCode, wrongRole.body).toBe(403);
      expect(wrongRole.json().error.code).toBe('INVITE_INVALID');
      expect(await membershipOf(room.id, S3.id)).toEqual([]);

      // WATCH stays reusable until rotation/expiry/close (spec 09 §5.4).
      expect((await invitationOf(stored.id))?.status).toBe('ACTIVE');
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('a PLAY code is single use and the second player is rejected', async () => {
    const { A, S1, S2 } = ctx.users;
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const created = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        role: 'PLAYER',
      });
      expect(created.statusCode, created.body).toBe(200);
      const code = created.json().data.code as string;
      expect(code).toMatch(CODE_RE);

      const first = await post('/api/v1/rooms/join', S1.accessToken, { code, role: 'PLAYER' });
      expect(first.statusCode, first.body).toBe(200);
      expect(
        (first.json().data.members as { role: string }[]).filter((m) => m.role === 'PLAYER'),
      ).toHaveLength(2);

      const second = await post('/api/v1/rooms/join', S2.accessToken, { code, role: 'PLAYER' });
      expect(second.statusCode, second.body).toBe(403);
      expect(second.json().error.code).toBe('INVITE_INVALID');
      expect(await membershipOf(room.id, S2.id)).toEqual([]);

      const row = await invitationOf(created.json().data.id as string);
      expect(row?.status).toBe('CONSUMED');
      expect(row?.consumed_by).toBe(S1.id);
      expect(row?.resolved_at).not.toBeNull();
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('rotation bumps the watch epoch and invalidates the previous code and token', async () => {
    const { A, S1 } = ctx.users;
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const first = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: true,
      });
      const oldCode = first.json().data.code as string;
      const oldToken = first.json().data.token as string;
      const second = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: true,
      });
      const newCode = second.json().data.code as string;

      const versions = await ctx.pool.query<{ watch_epoch: number; status: string; epoch: number }>(
        `SELECT r.watch_epoch, i.status, i.epoch
           FROM public.rooms r
           JOIN public.invitations i ON i.room_id = r.id
          WHERE r.id = $1
          ORDER BY i.epoch`,
        [room.id],
      );
      expect(versions.rows[0]).toMatchObject({ watch_epoch: 2, status: 'REVOKED', epoch: 1 });
      expect(versions.rows[1]).toMatchObject({ watch_epoch: 2, status: 'ACTIVE', epoch: 2 });

      for (const locator of [{ code: oldCode }, { token: oldToken }]) {
        const stale = await post('/api/v1/rooms/join', S1.accessToken, {
          ...locator,
          role: 'SPECTATOR',
        });
        expect(stale.statusCode, `stale ${JSON.stringify(locator)}: ${stale.body}`).toBe(403);
        expect(stale.json().error.code).toBe('INVITE_INVALID');
      }
      expect(await membershipOf(room.id, S1.id)).toEqual([]);

      const fresh = await post('/api/v1/rooms/join', S1.accessToken, {
        code: newCode,
        role: 'SPECTATOR',
      });
      expect(fresh.statusCode, fresh.body).toBe(200);

      // A non-rotating re-issue keeps the cohort epoch but still supersedes the code.
      const reissued = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: false,
      });
      const after = await ctx.pool.query<{ watch_epoch: number }>(
        'SELECT watch_epoch FROM public.rooms WHERE id = $1',
        [room.id],
      );
      expect(after.rows[0]!.watch_epoch).toBe(2);
      expect(reissued.json().data.code).not.toBe(newCode);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('an expired grant is INVITE_INVALID on join and listed EXPIRED for its recipient', async () => {
    const { A, B, S1 } = ctx.users;
    await makeFriends(A, B);
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const direct = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        recipientId: B.id,
      });
      const directId = direct.json().data.id as string;
      const watch = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: false,
      });
      const code = watch.json().data.code as string;

      // Backdate both timestamps: invitations_dates_check requires expires_at > created_at.
      await ctx.pool.query(
        `UPDATE public.invitations
            SET created_at = now() - interval '2 minutes', expires_at = now() - interval '1 minute'
          WHERE room_id = $1`,
        [room.id],
      );

      const inbox = await get('/api/v1/invitations', B.accessToken);
      expect(inbox.statusCode).toBe(200);
      expect(
        (inbox.json().data as { id: string; status: string }[]).find((i) => i.id === directId),
      ).toMatchObject({ status: 'EXPIRED' });
      const expired = await invitationOf(directId);
      expect(expired?.status).toBe('EXPIRED');
      expect(expired?.resolved_at).not.toBeNull();

      const respond = await post(`/api/v1/invitations/${directId}/respond`, B.accessToken, {
        accept: true,
      });
      expect(respond.statusCode, respond.body).toBe(403);
      expect(respond.json().error.code).toBe('INVITE_INVALID');

      const join = await post('/api/v1/rooms/join', S1.accessToken, { code, role: 'SPECTATOR' });
      expect(join.statusCode, join.body).toBe(403);
      expect(join.json().error.code).toBe('INVITE_INVALID');
      expect(await membershipOf(room.id, S1.id)).toEqual([]);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('re-issuing a direct invite reuses the ACTIVE row and never touches the WATCH grant', async () => {
    const { A, B, S1 } = ctx.users;
    await makeFriends(A, B);
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      const watch = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
        rotate: false,
      });
      const watchId = (await ctx.pool.query<{ id: string }>(
        `SELECT id FROM public.invitations WHERE room_id = $1 AND role = 'WATCH'`,
        [room.id],
      )).rows[0]!.id;

      const first = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        recipientId: B.id,
      });
      const second = await post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, {
        recipientId: B.id,
      });
      expect(second.statusCode, second.body).toBe(200);
      expect(first.statusCode, first.body).toBe(200);

      // Exactly one ACTIVE direct row (the partial unique index holds); the
      // re-issued invitation is the one B can accept.
      const active = await ctx.pool.query<{ count: number }>(
        `SELECT count(*)::int AS count FROM public.invitations
          WHERE room_id = $1 AND recipient_id = $2 AND status = 'ACTIVE'`,
        [room.id, B.id],
      );
      expect(active.rows[0]!.count).toBe(1);

      // Two simultaneous invites for the same recipient: the room lock serializes the
      // transactions, so both must answer 200 and the recipient must still have one
      // ACTIVE row (the upsert reuses it instead of inserting a duplicate).
      const [concurrentA, concurrentB] = await Promise.all([
        post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, { recipientId: B.id }),
        post(`/api/v1/rooms/${room.id}/invitations`, A.accessToken, { recipientId: B.id }),
      ]);
      expect([concurrentA.statusCode, concurrentB.statusCode], concurrentA.body).toEqual([200, 200]);
      const afterRace = await ctx.pool.query<{ count: number }>(
        `SELECT count(*)::int AS count FROM public.invitations
          WHERE room_id = $1 AND recipient_id = $2 AND status = 'ACTIVE'`,
        [room.id, B.id],
      );
      expect(afterRace.rows[0]!.count).toBe(1);

      // Superseding the direct row must not touch the share grant beside it.
      expect((await invitationOf(watchId))?.status).toBe('ACTIVE');
      const byCode = await post('/api/v1/rooms/join', S1.accessToken, {
        code: watch.json().data.code as string,
        role: 'SPECTATOR',
      });
      expect(byCode.statusCode, byCode.body).toBe(200);

      const accepted = await post(
        `/api/v1/invitations/${second.json().data.id as string}/respond`,
        B.accessToken,
        { accept: true },
      );
      expect(accepted.statusCode, accepted.body).toBe(200);
      expect(await membershipOf(room.id, B.id)).toEqual([{ role: 'PLAYER', side: 'BLACK' }]);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('unknown locators answer 403 INVITE_INVALID instead of leaking a Postgres error', async () => {
    const { A, B } = ctx.users;
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    try {
      for (const locator of [{ code: 'ZZZZZZZZ' }, { token: 'not-a-real-token' }] as const) {
        const denied = await post('/api/v1/rooms/join', B.accessToken, { ...locator, role: 'PLAYER' });
        expect(denied.statusCode, `${JSON.stringify(locator)} body: ${denied.body}`).toBe(403);
        expect(denied.json().error.code).toBe('INVITE_INVALID');
      }
      expect(await membershipOf(room.id, B.id)).toEqual([]);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });

  it('closing the room invalidates an outstanding watch grant', async () => {
    const { A, S1 } = ctx.users;
    const room = await createRoom(A.accessToken, 'CODE_ONLY');
    const grant = await post(`/api/v1/rooms/${room.id}/watch-code`, A.accessToken, {
      rotate: false,
    });
    const code = grant.json().data.code as string;

    await closeRoom(A.accessToken, room.id);

    const denied = await post('/api/v1/rooms/join', S1.accessToken, { code, role: 'SPECTATOR' });
    expect(denied.statusCode, denied.body).toBe(403);
    expect(denied.json().error.code).toBe('INVITE_INVALID');
    expect(await membershipOf(room.id, S1.id)).toEqual([]);
  });

  it('an unonboarded session is rejected with ONBOARDING_REQUIRED until complete-profile', async () => {
    const env = resolveTestEnv();
    const email = `onb_inv_${ctx.runId}@local.test`;
    const adminHeaders = {
      apikey: env.supabaseSecretKey,
      Authorization: `Bearer ${env.supabaseSecretKey}`,
      'Content-Type': 'application/json',
    };
    // Phone-only signup keeps profiles.username NULL (the email trigger requires one);
    // an email identity is attached afterwards without re-running the trigger.
    const created = await fetch(`${env.supabaseUrl}/auth/v1/admin/users`, {
      method: 'POST',
      headers: adminHeaders,
      body: JSON.stringify({
        phone: `+8492${crypto.randomInt(1000000, 9999999)}`,
        password: 'LocalTest12345',
        phone_confirm: true,
        user_metadata: { test_run_id: ctx.runId },
      }),
    });
    const createdBody = (await created.json().catch(() => null)) as { id?: string } | null;
    if (!created.ok || !createdBody?.id) {
      throw new Error(`[invitations] Admin createUser failed (${created.status}): ${await created.text()}`);
    }
    const attached = await fetch(`${env.supabaseUrl}/auth/v1/admin/users/${createdBody.id}`, {
      method: 'PUT',
      headers: adminHeaders,
      body: JSON.stringify({ email, email_confirm: true, password: 'LocalTest12345' }),
    });
    if (!attached.ok) {
      throw new Error(`[invitations] Admin attach email failed (${attached.status}): ${await attached.text()}`);
    }
    const accessToken = await signIn({ email, password: 'LocalTest12345' });
    const profile = await ctx.pool.query<{ username: string | null }>(
      'SELECT username FROM public.profiles WHERE user_id = $1',
      [createdBody.id],
    );
    expect(profile.rows[0]?.username).toBeNull();

    const { A } = ctx.users;
    const room = await createRoom(A.accessToken, 'PUBLIC');
    try {
      const gated = await post(`/api/v1/rooms/${room.id}/invitations`, accessToken, {
        role: 'PLAYER',
      });
      expect(gated.statusCode, gated.body).toBe(403);
      expect(gated.json().error.code).toBe('ONBOARDING_REQUIRED');

      // Exempt while unonboarded: /me reports the flag, complete-profile is reachable.
      const me = await get('/api/v1/me', accessToken);
      expect(me.statusCode).toBe(200);
      expect(me.json().data.onboardingRequired).toBe(true);

      const username = `xq_onb_${ctx.runId}`;
      const completed = await post('/api/v1/auth/complete-profile', accessToken, {
        username,
        displayName: 'Invitee',
      });
      expect(completed.statusCode, completed.body).toBe(200);

      const joined = await post('/api/v1/rooms/join', accessToken, {
        roomId: room.id,
        role: 'PLAYER',
      });
      expect(joined.statusCode, joined.body).toBe(200);
      expect(await membershipOf(room.id, createdBody.id)).toEqual([
        { role: 'PLAYER', side: 'BLACK' },
      ]);
    } finally {
      await closeRoom(A.accessToken, room.id);
    }
  });
});
