BEGIN;
SET LOCAL search_path=pg_catalog,public;
LOCK TABLE public.matches,public.match_events IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF (SELECT pg_catalog.md5(pg_catalog.pg_get_constraintdef(oid)) FROM pg_catalog.pg_constraint WHERE conrelid='public.matches'::pg_catalog.regclass AND conname='matches_status_and_outcome_invariants' AND contype='c' AND convalidated) IS DISTINCT FROM 'b065e4eab6b66eb703d4e215ab8d2c29'
 OR (SELECT pg_catalog.pg_get_indexdef(c.oid) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_index i ON i.indexrelid=c.oid WHERE c.oid=pg_catalog.to_regclass('public.match_start_token_unique') AND c.relowner='postgres'::pg_catalog.regrole AND i.indisvalid AND i.indisunique) IS DISTINCT FROM 'CREATE UNIQUE INDEX match_start_token_unique ON public.match_events USING btree (((payload ->> ''startToken''::text))) WHERE ((type = ''START''::text) AND ((payload ->> ''encoding''::text) = ''xiangqi-core-v1''::text))' THEN RAISE EXCEPTION 'Match metadata changed; rollback refused'; END IF;
 IF EXISTS(SELECT 1 FROM public.match_events WHERE type='START' AND payload->>'encoding'='xiangqi-core-v1') OR EXISTS(SELECT 1 FROM public.matches WHERE outcome->>'reason' IN('PERPETUAL_CHECK','DRAW_REPETITION','DRAW_NO_CAPTURE','DRAW_AGREEMENT')) THEN RAISE EXCEPTION 'Match feature writes exist; rollback refused'; END IF;
END $$;
DROP INDEX public.match_start_token_unique;
ALTER TABLE public.matches DROP CONSTRAINT matches_status_and_outcome_invariants;
ALTER TABLE public."matches" ADD CONSTRAINT "matches_status_and_outcome_invariants" CHECK ((((status = 'ACTIVE'::text) AND (outcome IS NULL) AND (ended_at IS NULL)) OR ((status = 'INTERRUPTED'::text) AND (ended_at IS NOT NULL) AND (ended_at >= created_at) AND (proposal IS NULL) AND (outcome IS NOT NULL) AND COALESCE(((jsonb_typeof(outcome) = 'object'::text) AND (outcome ? 'reason'::text) AND (outcome ? 'winner'::text) AND ((outcome ->> 'reason'::text) = ANY (ARRAY['BOTH_OFFLINE'::text, 'SERVER_RESTART'::text, 'AI_UNAVAILABLE'::text])) AND (jsonb_typeof((outcome -> 'winner'::text)) = 'null'::text)), false)) OR ((status = 'FINISHED'::text) AND (ended_at IS NOT NULL) AND (ended_at >= created_at) AND (proposal IS NULL) AND (outcome IS NOT NULL) AND COALESCE(((jsonb_typeof(outcome) = 'object'::text) AND (outcome ? 'reason'::text) AND (outcome ? 'winner'::text) AND ((((outcome ->> 'reason'::text) = ANY (ARRAY['AGREED_DRAW'::text, 'REPETITION'::text])) AND (jsonb_typeof((outcome -> 'winner'::text)) = 'null'::text)) OR (((outcome ->> 'reason'::text) = ANY (ARRAY['CHECKMATE'::text, 'STALEMATE'::text, 'TIMEOUT'::text, 'RESIGN'::text, 'DISCONNECT'::text])) AND ((outcome ->> 'winner'::text) = ANY (ARRAY['RED'::text, 'BLACK'::text]))))), false))));
COMMIT;
