import { describe, expect, it } from "vitest";
import {
  initialPosition,
  isInCheck,
  legalMoves,
  perft,
  playMove,
  parsePosition,
} from "../src/index.js";
import { fixture, square } from "./fixtures.js";

describe("general safety and move application (T07)", () => {
  it("cannot evaluate check without the side's general", () => {
    expect(() => isInCheck(fixture([["black", "king", 4, 0]]), "red")).toThrow(
      "INVALID_POSITION",
    );
  });

  it("rejects exposing facing generals and never permits capturing a general", () => {
    const position = fixture([
      ["black", "king", 4, 0],
      ["red", "king", 4, 9],
      ["red", "rook", 4, 5],
    ]);
    expect(isInCheck(position, "red")).toBe(false);
    expect(legalMoves(position)).not.toContainEqual({ from: 49, to: 48 });
    expect(legalMoves(position)).not.toContainEqual({ from: 49, to: 4 });
    expect(legalMoves(position)).toContainEqual({ from: 49, to: 40 });
    expect(
      isInCheck(
        fixture([
          ["black", "king", 4, 0],
          ["red", "king", 4, 9],
        ]),
        "red",
      ),
    ).toBe(true);
  });

  it("permits interposing, capturing the checking rook or escaping with the general", () => {
    const position = fixture([
      ["black", "king", 5, 0],
      ["red", "king", 4, 9],
      ["black", "rook", 4, 5],
      ["red", "rook", 0, 8],
      ["red", "rook", 0, 5],
    ]);
    expect(isInCheck(position, "red")).toBe(true);
    const moves = legalMoves(position);
    expect(moves).toContainEqual({ from: 72, to: 76 });
    expect(moves).toContainEqual({ from: 45, to: 49 });
    expect(moves).toContainEqual({ from: 85, to: 84 });
    expect(moves).not.toContainEqual({ from: 72, to: 73 });
  });

  it("recognizes a cannon check only with one screen", () => {
    const bare = fixture([
      ["black", "king", 5, 0],
      ["red", "king", 4, 9],
      ["black", "cannon", 4, 3],
    ]);
    expect(isInCheck(bare, "red")).toBe(false);
    bare.board[49] = { side: "red", type: "pawn" };
    expect(isInCheck(bare, "red")).toBe(true);
    bare.board[67] = { side: "red", type: "pawn" };
    expect(isInCheck(bare, "red")).toBe(false);
  });

  it("does not treat a horse with its leg blocked as checking", () => {
    const position = fixture([
      ["black", "king", 5, 0],
      ["red", "king", 4, 9],
      ["black", "horse", 3, 7],
    ]);
    expect(isInCheck(position, "red")).toBe(true);
    position.board[square(3, 8)] = { side: "red", type: "advisor" };
    expect(isInCheck(position, "red")).toBe(false);
  });

  it("applies a move without mutation and increments no-capture and move counters", () => {
    const position = initialPosition();
    const before = structuredClone(position);
    const next = playMove(position, { from: 54, to: 45 });
    expect(position).toEqual(before);
    expect(next.board[54]).toBeNull();
    expect(next.board[45]).toEqual({ side: "red", type: "pawn" });
    expect(next.turn).toBe("black");
    expect(next.halfmove).toBe(1);
    expect(next.fullmove).toBe(1);
    const afterBlack = playMove(next, { from: 27, to: 36 });
    expect(afterBlack.fullmove).toBe(2);
    expect(afterBlack.halfmove).toBe(2);
  });

  it("resets the no-capture count on capture, including a pawn capture", () => {
    const position = fixture(
      [
        ["black", "king", 5, 0],
        ["red", "king", 4, 9],
        ["red", "pawn", 0, 4],
        ["black", "pawn", 0, 3],
      ],
      "red",
      119,
    );
    const next = playMove(position, { from: 36, to: 27 });
    expect(next.halfmove).toBe(0);
    expect(next.board[27]).toEqual({ side: "red", type: "pawn" });
  });

  it.each([
    { from: 54, to: 36 },
    { from: 0, to: 9 },
    { from: -1, to: 0 },
    { from: 54, to: 90 },
    { from: 54, to: 54 },
    { from: 54.5, to: 45 },
  ])("rejects an illegal move without changing the position: %o", (move) => {
    const position = initialPosition();
    const before = structuredClone(position);
    expect(() => playMove(position, move)).toThrow("ILLEGAL_MOVE");
    expect(position).toEqual(before);
  });

  it("rejects a geometrically valid move exposing the general", () => {
    const position = fixture([
      ["black", "king", 4, 0],
      ["red", "king", 4, 9],
      ["red", "rook", 4, 5],
    ]);
    const before = structuredClone(position);
    expect(() => playMove(position, { from: 49, to: 48 })).toThrow(
      "ILLEGAL_MOVE",
    );
    expect(position).toEqual(before);
  });
});

describe("independent published perft (AC-04.1.1, T10)", () => {
  // Author's measurements, checked 11/10/2026, not generated by this library:
  // https://talkchess.com/viewtopic.php?t=76430 (Maksim Korzh, 27/01/2021).
  it.each([
    [0, 1],
    [1, 44],
    [2, 1920],
    [3, 79666],
  ])("counts opening depth %i as %i", (depth, nodes) => {
    expect(perft(initialPosition(), depth!)).toBe(nodes);
  });

  it.each([
    [1, 38],
    [2, 1128],
    [3, 43929],
  ])(
    "counts an independently published tactical midgame depth %i as %i",
    (depth, nodes) => {
      const position = parsePosition(
        "r1ba1a3/4kn3/2n1b4/pNp1p1p1p/4c4/6P2/P1P2R2P/1CcC5/9/2BAKAB2 w - - 0 1",
      );
      expect(perft(position, depth!)).toBe(nodes);
    },
  );
});
