BEGIN;
SET LOCAL search_path=pg_catalog,public;
LOCK TABLE public.matches,public.match_events IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF (SELECT pg_catalog.md5(pg_catalog.pg_get_constraintdef(oid)) FROM pg_catalog.pg_constraint WHERE conrelid='public.matches'::pg_catalog.regclass AND conname='matches_status_and_outcome_invariants' AND contype='c' AND convalidated) IS DISTINCT FROM '559020c567790e53058a519863fb10a0' THEN RAISE EXCEPTION 'Match outcome metadata differs from audited baseline'; END IF;
END $$;
ALTER TABLE public.matches DROP CONSTRAINT matches_status_and_outcome_invariants;
ALTER TABLE public."matches" ADD CONSTRAINT "matches_status_and_outcome_invariants" CHECK ((((status = 'ACTIVE'::text) AND (outcome IS NULL) AND (ended_at IS NULL)) OR ((status = 'INTERRUPTED'::text) AND (ended_at IS NOT NULL) AND (ended_at >= created_at) AND (proposal IS NULL) AND (outcome IS NOT NULL) AND COALESCE(((jsonb_typeof(outcome) = 'object'::text) AND (outcome ? 'reason'::text) AND (outcome ? 'winner'::text) AND ((outcome ->> 'reason'::text) = ANY (ARRAY['BOTH_OFFLINE'::text, 'SERVER_RESTART'::text, 'AI_UNAVAILABLE'::text])) AND (jsonb_typeof((outcome -> 'winner'::text)) = 'null'::text)), false)) OR ((status = 'FINISHED'::text) AND (ended_at IS NOT NULL) AND (ended_at >= created_at) AND (proposal IS NULL) AND (outcome IS NOT NULL) AND COALESCE(((jsonb_typeof(outcome) = 'object'::text) AND (outcome ? 'reason'::text) AND (outcome ? 'winner'::text) AND ((((outcome ->> 'reason'::text) = ANY (ARRAY['AGREED_DRAW'::text, 'REPETITION'::text, 'DRAW_REPETITION'::text, 'DRAW_NO_CAPTURE'::text, 'DRAW_AGREEMENT'::text])) AND (jsonb_typeof((outcome -> 'winner'::text)) = 'null'::text)) OR (((outcome ->> 'reason'::text) = ANY (ARRAY['CHECKMATE'::text, 'STALEMATE'::text, 'TIMEOUT'::text, 'RESIGN'::text, 'DISCONNECT'::text])) AND ((outcome ->> 'winner'::text) = ANY (ARRAY['RED'::text, 'BLACK'::text])))) OR (((outcome ->> 'reason'::text) = 'PERPETUAL_CHECK'::text) AND (((outcome ->> 'winner'::text) = ANY (ARRAY['RED'::text, 'BLACK'::text])) OR (jsonb_typeof((outcome -> 'winner'::text)) = 'null'::text)))), false))));
CREATE UNIQUE INDEX match_start_token_unique ON public.match_events ((payload->>'startToken')) WHERE type='START' AND payload->>'encoding'='xiangqi-core-v1';
COMMIT;
